// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyizvwuetbfyxbftvzew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5aXp2d3VldGJmeXhiZnR2emV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTE2MTYsImV4cCI6MjA2MzgyNzYxNn0.nPs2rrS-GI5C-TyZmCdgTqtbcVylhRblHhf_tkTNaHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);